#!/bin/bash

echo "clearing recently used"
	if [ -f "$HOME/.local/share/psi/.local/share/recently-used.xbel" ]; then
		mv "$HOME/.local/share/psi/.local/share/recently-used.xbel" "$HOME/.local/share/psi/.local/share/recently-used.xbel.bak"
	fi
	touch "$HOME/.local/share/psi/.local/share/recently-used.xbel"
	echo "<?xml version="1.0" encoding="UTF-8"?>\n<xbel version="1.0"\nxmlns:bookmark="http://www.freedesktop.org/standards/desktop-bookmarks"\nxmlns:mime="http://www.freedesktop.org/standards/shared-mime-info"\n></xbel>\n
 " > "$HOME/.local/share/psi/.local/share/recently-used.xbel"
	chmod a+xwr "$HOME/.local/share/psi/.local/share/recently-used.xbel"

echo "clearing tmp"
	rm -rf "/tmp/*"
	
echo "clearing thumbnails"
	rm -rf "$HOME/.thumbnails/*"
	
echo "clearing trash"
	rm -r "$HOME/.local/share/Trash/files"
	
zenity --question --window-icon="/Images/logo.png" --text "Do you really want to remove the orphan libraries? (Warning: Dangerous Command!"
	if [ $? -eq 0 ]; then
		if [ ! "$(which deborphan)" ]; then # Missing Dependency
			apt-get -y install deborphan
		fi
		apt-get -y --purge remove `deborphan`
	fi