#!/bin/bash
#
# get a git subfolder like git-subdir URL
# e.g. git-subdir https://github.com/freddii/liveTV/tree/master/liveTV_png
#
URL=$1
#echo $URL
NEW_URL=$(echo $URL | sed 's|/tree/master|.git/trunk|g')
#echo $NEW_URL
svn export $NEW_URL