#!/usr/bin/env bash
text="$(xsel -o)"
translate="$(wget -U "Mozilla/5.0" -qO - "http://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=en&dt=t&q=$(echo $text | sed "s/[\"'<>]//g")" | sed "s/,,,0]],,.*//g" | awk -F'"' '{print $2, $6}')"
echo -e "text :  " "$text"'\n' > /tmp/notitrans
echo "translation :  " "$translate" >> /tmp/notitrans
zenity --text-info --title="translator" --filename=/tmp/notitrans
